title: Irriduino2
description: Arduino project for an irrigation of a garden
name: Roberto Alonso
# author:
#     name: Roberto Alonso
#     avatar: "https://avatars3.githubusercontent.com/u/3586109"
#     github: "ralonsoafl"
repository: "Ralonsoafl/Irriduino"
# url: "https://ralonsoafl.github.io/Irriduino"
# baseurl: "/Irriduino"
logo: /assets/img/logo.png
theme: jekyll-theme-leap-day
show_downloads: true
# exclude:
#     - LICENSE
#     - README.md
#     - assets/img